force-app/main/default/objects/LabBooking__c/LabBooking__c.object-meta.xml
<CustomObject>
    <label>实验室预约</label>
    <nameField>
        <displayFormat>LB-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/LabBooking__c/fields/LabAddress__c.field-meta.xml
<CustomField>
    <fullName>LabAddress__c</fullName>
    <label>实验室地址</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>备注</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>仅在“需要批准”字段勾选时生效。</inlineHelpText>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LB1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/LabBookingApplication__c.object-meta.xml
<CustomObject>
    <label>实验室预约申请</label>
    <nameField>
        <displayFormat>LBA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LabBookingApplication__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>批准状态</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatusGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/BookedLab__c.field-meta.xml
<CustomField>
    <fullName>BookedLab__c</fullName>
    <label>预约的实验室</label>
    <referenceTo>LabBooking__c</referenceTo>
    <relationshipLabel>预约申请</relationshipLabel>
    <relationshipName>LabBookingApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/LabAddress__c.field-meta.xml
<CustomField>
    <fullName>LabAddress__c</fullName>
    <formula>BookedLab__r.LabAddress__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>实验室地址</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>CASE(
				TEXT(BookedLab__r.Location__c),
				&apos;MingdeBuilding&apos;,&apos;明德楼&apos;,
				&apos;BoyaBuilding&apos;,&apos;伯牙楼&apos;,
				&apos;HongwenBuilding&apos;,&apos;弘文楼&apos;,
				&apos;DaqianBuilding&apos;,&apos;大千楼&apos;,
				&apos;GezhiBuilding&apos;,&apos;格致楼&apos;,
				&apos;TrainingCenter&apos;,&apos;培训中心&apos;,
				&apos;X1stPracticalTrainingBuilding&apos;,&apos;第一实训楼&apos;,
				&apos;X2ndPracticalTrainingBuilding&apos;,&apos;第二实训楼&apos;,
				&apos;X3rdPracticalTrainingBuilding&apos;,&apos;第三实训楼&apos;,
				&apos;X1stPlayground&apos;,&apos;第一运动场&apos;,
				&apos;X2ndPlayground&apos;,&apos;第二运动场&apos;,
				&apos;X3rdPlayground&apos;,&apos;第三运动场&apos;,
				&apos;X4thPlayground&apos;,&apos;第四运动场&apos;,
				&apos;X5thPlayground&apos;,&apos;第五运动场&apos;,
				&apos;GroundTrackField&apos;,&apos;田径场&apos;,
				TEXT(BookedLab__r.Location__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>地点</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>此字段将在保存后自动从“预约的实验室”中的“审批人”字段取值，无需手动填写。</inlineHelpText>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LBA1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/TeachingSupplyBorrowingApplication__c.object-meta.xml
<CustomObject>
    <label>教学用品借用申请</label>
    <nameField>
        <displayFormat>TSBA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Borrower__c.field-meta.xml
<CustomField>
    <fullName>Borrower__c</fullName>
    <inlineHelpText>若借用的物品用于课堂教学，请填写上课教师的姓名。</inlineHelpText>
    <label>借用人</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingEndClassTimes__c.field-meta.xml
<CustomField>
    <fullName>BorrowingEndClassTimes__c</fullName>
    <label>借用结束节次</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassTimesGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingEndDate__c.field-meta.xml
<CustomField>
    <fullName>BorrowingEndDate__c</fullName>
    <label>借用结束日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingEndDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>BorrowingEndDateAndTime__c</fullName>
    <inlineHelpText>按日期和节次借用时，此字段将在保存后自动计算，无需填写。</inlineHelpText>
    <label>借用结束时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartClassTimes__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartClassTimes__c</fullName>
    <label>借用开始节次</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassTimesGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartDate__c</fullName>
    <label>借用开始日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartDateAndTime__c</fullName>
    <inlineHelpText>按日期和节次借用时，此字段将在保存后自动计算，无需填写。</inlineHelpText>
    <label>借用开始时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ClassRoom__c.field-meta.xml
<CustomField>
    <fullName>ClassRoom__c</fullName>
    <label>教室</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/IsBorrowed__c.field-meta.xml
<CustomField>
    <fullName>IsBorrowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>是否借出</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/IsReturned__c.field-meta.xml
<CustomField>
    <fullName>IsReturned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>是否归还</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>地点</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TeachingLocationGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>联系电话</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReceiveAddress__c.field-meta.xml
<CustomField>
    <fullName>ReceiveAddress__c</fullName>
    <inlineHelpText>领取地址会在审批通过后显示，无需填写。</inlineHelpText>
    <label>领取地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReceiveContact__c.field-meta.xml
<CustomField>
    <fullName>ReceiveContact__c</fullName>
    <inlineHelpText>领取联系人会在审批通过后显示，无需填写。</inlineHelpText>
    <label>领取联系人</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReceiveContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ReceiveContactPhone__c</fullName>
    <inlineHelpText>领取联系方式会在审批通过后显示，无需填写。</inlineHelpText>
    <label>领取联系方式</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Remark__c.field-meta.xml
<CustomField>
    <fullName>Remark__c</fullName>
    <label>备注</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReturnAddress__c.field-meta.xml
<CustomField>
    <fullName>ReturnAddress__c</fullName>
    <inlineHelpText>归还地址会在审批通过后显示，无需填写。</inlineHelpText>
    <label>归还地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReturnContact__c.field-meta.xml
<CustomField>
    <fullName>ReturnContact__c</fullName>
    <inlineHelpText>归还联系人会在审批通过后显示，无需填写。</inlineHelpText>
    <label>归还联系人</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReturnContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ReturnContactPhone__c</fullName>
    <inlineHelpText>归还联系方式会在审批通过后显示，无需填写。</inlineHelpText>
    <label>归还联系方式</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/SecondaryCollegeLookup__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollegeLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>教学用品借用申请(学院维度)</relationshipLabel>
    <relationshipName>TSBASecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/TeachingSupply__c.field-meta.xml
<CustomField>
    <fullName>TeachingSupply__c</fullName>
    <label>物品</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>TeachingSupplyGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatusGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>草稿</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <label>审批中</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
        <label>已批准</label>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>已拒绝</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>已取消</label>
    </customValue>
    <masterLabel>批准状态</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ClassTimesGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>1(8:20-9:05)</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>2(9:15-10:00)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>3(10:20-11:05)</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>4(11:15-12:00)</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>5(13:50-14:35)</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>6(14:45-15:30)</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>7(15:50-16:35)</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>8(16:45-17:30)</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>9(19:00-19:45)</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10(19:55-20:40)</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11(20:50-21:35)</label>
    </customValue>
    <masterLabel>上课节次</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TeachingLocationGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MingdeBuilding</fullName>
        <label>明德楼</label>
    </customValue>
    <customValue>
        <fullName>BoyaBuilding</fullName>
        <label>伯牙楼</label>
    </customValue>
    <customValue>
        <fullName>HongwenBuilding</fullName>
        <label>弘文楼</label>
    </customValue>
    <customValue>
        <fullName>DaqianBuilding</fullName>
        <label>大千楼</label>
    </customValue>
    <customValue>
        <fullName>GezhiBuilding</fullName>
        <label>格致楼</label>
    </customValue>
    <customValue>
        <fullName>TrainingCenter</fullName>
        <label>培训中心</label>
    </customValue>
    <customValue>
        <fullName>X1stPracticalTrainingBuilding</fullName>
        <label>第一实训楼</label>
    </customValue>
    <customValue>
        <fullName>X2ndPracticalTrainingBuilding</fullName>
        <label>第二实训楼</label>
    </customValue>
    <customValue>
        <fullName>X3rdPracticalTrainingBuilding</fullName>
        <label>第三实训楼</label>
    </customValue>
    <customValue>
        <fullName>X1stPlayground</fullName>
        <label>第一运动场</label>
    </customValue>
    <customValue>
        <fullName>X2ndPlayground</fullName>
        <label>第二运动场</label>
    </customValue>
    <customValue>
        <fullName>X3rdPlayground</fullName>
        <label>第三运动场</label>
    </customValue>
    <customValue>
        <fullName>X4thPlayground</fullName>
        <label>第四运动场</label>
    </customValue>
    <customValue>
        <fullName>X5thPlayground</fullName>
        <label>第五运动场</label>
    </customValue>
    <customValue>
        <fullName>GroundTrackField</fullName>
        <label>田径场</label>
    </customValue>
    <masterLabel>教学地点</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TeachingSupplyGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>话筒</fullName>
    </customValue>
    <customValue>
        <fullName>扩音器</fullName>
    </customValue>
    <customValue>
        <fullName>HDMI转VGA转换器</fullName>
    </customValue>
    <customValue>
        <fullName>网线</fullName>
    </customValue>
    <customValue>
        <fullName>百兆交换机(5口)</fullName>
    </customValue>
    <customValue>
        <fullName>录音机</fullName>
    </customValue>
    <customValue>
        <fullName>录像机</fullName>
    </customValue>
    <customValue>
        <fullName>万用表</fullName>
    </customValue>
    <customValue>
        <fullName>生物用显微镜</fullName>
    </customValue>
    <customValue>
        <fullName>秒表</fullName>
    </customValue>
    <customValue>
        <fullName>电焊机</fullName>
    </customValue>
    <customValue>
        <fullName>烧杯</fullName>
    </customValue>
    <customValue>
        <fullName>量筒</fullName>
    </customValue>
    <customValue>
        <fullName>乒乓球拍</fullName>
    </customValue>
    <customValue>
        <fullName>羽毛球拍</fullName>
    </customValue>
    <customValue>
        <fullName>足球</fullName>
    </customValue>
    <customValue>
        <fullName>篮球</fullName>
    </customValue>
    <masterLabel>教学用品</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RS_AnonymousApexExecute.cls
/**
 * 
 */
public with sharing class RS_AnonymousApexExecute {
    public static void main_031301(){
        List<TeachingSupplyBorrowingApplication__c> lstBorrowingApplication = [
            SELECT Id, OwnerId, IsDeleted, Name, RecordTypeId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastViewedDate, LastReferencedDate, BorrowingStartDate__c, ClassRoom__c, Phone__c, Quantity__c, IsReturned__c, Borrower__c, SecondaryCollegeLookup__c, Remark__c, Location__c, ApprovalStatus__c, IsBorrowed__c, BorrowingEndDate__c, BorrowingStartClassTimes__c, BorrowingEndClassTimes__c, BorrowingStartDateAndTime__c, BorrowingEndDateAndTime__c, TeachingSupply__c 
            FROM TeachingSupplyBorrowingApplication__c
            WHERE Id = 'a0F5i00000BFNmlEAH'
        ];
        RS_TeachingSupply_Before_Hdl.setBorrowingStartAndEndDatetime(lstBorrowingApplication);
        for (TeachingSupplyBorrowingApplication__c objBorrowingApplication : lstBorrowingApplication) {
            System.debug('objBorrowingApplication.BorrowingStartDateAndTime__c -> ' + objBorrowingApplication.BorrowingStartDateAndTime__c);
            System.debug('objBorrowingApplication.BorrowingEndDateAndTime__c -> ' + objBorrowingApplication.BorrowingEndDateAndTime__c);
        }
    }

    public static void main_031701(){
        List<TeachingSupplyBorrowingApplication__c> lstBorrowingApplication = [
            SELECT Id, OwnerId, IsDeleted, Name, RecordTypeId, CreatedDate, CreatedById, LastModifiedDate, LastModifiedById, SystemModstamp, LastActivityDate, LastViewedDate, LastReferencedDate, BorrowingStartDate__c, ClassRoom__c, Phone__c, Quantity__c, IsReturned__c, Borrower__c, SecondaryCollegeLookup__c, Remark__c, Location__c, ApprovalStatus__c, IsBorrowed__c, BorrowingEndDate__c, ReceiveAddress__c, BorrowingStartClassTimes__c, BorrowingEndClassTimes__c, BorrowingStartDateAndTime__c, BorrowingEndDateAndTime__c, TeachingSupply__c, ReceiveContact__c, ReceiveContactPhone__c, ReturnAddress__c, ReturnContact__c, ReturnContactPhone__c 
            FROM TeachingSupplyBorrowingApplication__c
            WHERE Id = 'a0F5i00000BFUMVEA5'
        ];
        RS_TeachingSupply_Before_Hdl.setReceiveAndReutrnContact(lstBorrowingApplication);
        for (TeachingSupplyBorrowingApplication__c objBorrowingApplication : lstBorrowingApplication) {
            System.debug('objBorrowing.Id -> ' + objBorrowingApplication.Id);
            System.debug('objBorrowing.ReceiveContact__c -> ' + objBorrowingApplication.ReceiveContact__c);
            System.debug('objBorrowing.ReceiveContactPhone__c -> ' + objBorrowingApplication.ReceiveContactPhone__c);
            System.debug('objBorrowing.ReceiveAddress__c -> ' + objBorrowingApplication.ReceiveAddress__c);
            System.debug('objBorrowing.ReturnContact__c -> ' + objBorrowingApplication.ReturnContact__c);
            System.debug('objBorrowing.ReturnContactPhone__c -> ' + objBorrowingApplication.ReturnContactPhone__c);
            System.debug('objBorrowing.ReturnAddress__c -> ' + objBorrowingApplication.ReturnAddress__c);
        }
    }

    public static void main_230328_01(){
        Map<String, Object> mapPicklistValues = RS_ApexUtil_Cmn.getPicklistDescribe('LabBooking__c', 'Location__c');
        System.debug('mapPicklistValues -> ' + mapPicklistValues);
    }

    public static void main_230328_02(){
        Map<String, Object> mapPicklistDescribe = RS_ApexUtil_Cmn.getPicklistDescribe('LabBookingApplication__c', 'ApprovalStatus__c');
        System.debug('mapPicklistDescribe -> ' + mapPicklistDescribe);
    }

    public static void main_230331(){
        RS_LabBooking_Ctl.bookingRequest('a005i00000B3p3YAAR');
    }

    public static void main_230405(){
        List<LabBookingApplication__c> lstLabBookingApplication = [SELECT Id, Name, RecordTypeId, CreatedById, LastModifiedById, BookedLab__c, Location__c, LabAddress__c, X1stApprover__c FROM LabBookingApplication__c];
        RS_LabBookingApplication_Before_Hdl.setApprover(lstLabBookingApplication);
    }

    public static void main_230429(){
        RS_DataPrepare_Tmp.updateLeaveApplicationLookup();
    }

    public static void main_230610(){
        RS_ResponseResult res = RS_Leave_Ctl.getApprovalSteps('a0J5i00000B32u1EAB');
        System.debug('Res -> ' + res);
    }

    public static void main_230613(){
        RS_Leave_Sch objLeaveScheduler = new RS_Leave_Sch('notify');
        String sch = '0 0 22 * * ?';
        String jobID = System.schedule('邮件通知超时未归还的教学用品借用申请', sch, objLeaveScheduler);
    }

    public static void main_230624(){
        List<String> lstAtPhone = new List<String>();
        lstAtPhone.add('123');
        RS_TeachingSupply_Pst.sendDingtalkNotice('测试一条消息', lstAtPhone);
    }

    public static void main_230625(){
        RS_Leave_Sch objLeaveScheduler = new RS_Leave_Sch('notify');
        List<TeachingSupplyBorrowingApplication__c> lstTimeoutUnreturnedApplication = objLeaveScheduler.notifyTimeoutUnreturned();
        String strDingtalkMsg = '已对超时未归还的用户发送电子邮件通知。\n';
        strDingtalkMsg += '总条数：' + lstTimeoutUnreturnedApplication.size() + '条';
        RS_TeachingSupply_Pst.sendDingtalkNotice(strDingtalkMsg, null);
    }

    public static void main_230701(){
        Date dateInstance = Date.newInstance(2023, 7, 1);
        Datetime gmtDatetime = RS_ApexUtil_Cmn.localDateToGmtDatetime(dateInstance);
        System.debug('dateInstance -> ' + dateInstance);
        System.debug('gmtDatetime -> ' + gmtDatetime);
    }

    public static void execute(){
        RS_AnonymousApexExecute.main_230701();
    }
}