force-app/main/default/objects/LabBooking__c/LabBooking__c.object-meta.xml
<CustomObject>
    <label>实验室预约</label>
    <nameField>
        <displayFormat>LB-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/LabBooking__c/fields/IsApprovalRequired__c.field-meta.xml
<CustomField>
    <fullName>IsApprovalRequired__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>勾选此项时，学生创建的预约申请需要审批人审批。</inlineHelpText>
    <label>需要批准</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>仅在“需要批准”字段勾选时生效。</inlineHelpText>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LB1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/LabBookingApplication__c.object-meta.xml
<CustomObject>
    <label>实验室预约申请</label>
    <nameField>
        <displayFormat>LBA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LabBookingApplication__c/fields/BookedLab__c.field-meta.xml
<CustomField>
    <fullName>BookedLab__c</fullName>
    <label>预约的实验室</label>
    <referenceTo>LabBooking__c</referenceTo>
    <relationshipLabel>预约申请</relationshipLabel>
    <relationshipName>LabBookingApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>此字段将在保存后自动从“预约的实验室”中的“审批人”字段取值，无需手动填写。</inlineHelpText>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LBA1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RS_LabBookingApplication_Before_Hdl.cls
/**
 * @description: LabBookingApplication__c BeforeInsert, BeforeUpdate trigger handler
 * @author: AnonyEast
 * @date: 2023-04-05
 */
public with sharing class RS_LabBookingApplication_Before_Hdl implements Triggers.Handler {
    public void handle() {
        try {
            // 更新后的对象
            List<LabBookingApplication__c> lstNewLabBookingApplication = (List<LabBookingApplication__c>)Trigger.new;
            // 更新前的对象
            Map<Id, LabBookingApplication__c> mapOldLabBookingApplication = (Map<Id, LabBookingApplication__c>)Trigger.oldMap;
            // 审批人赋值
            setApprover(lstNewLabBookingApplication);
        } catch (Exception ex) {
            RS_Logger_Cmn.createLog('LabBookingApplication_BeforeTrg_Exception',ex,'RS_LabBookingApplication_Before_Hdl.handle');
        }
    }

    /**
     * @description 审批人字段赋值
     * @param lstLabBookingApplication 实验室借用申请实例列表
     */
    public static void setApprover(List<LabBookingApplication__c> lstLabBookingApplication) {
        // 获取需要批准的实验室审批人
        Map<Id, LabBooking__c> mapLabBooking = new Map<Id, LabBooking__c>([
            SELECT 
                Id, IsApprovalRequired__c, X1stApprover__c 
            FROM 
                LabBooking__c 
            WHERE 
                IsApprovalRequired__c = true  
        ]);
        // 审批人赋值
        for (LabBookingApplication__c objLabBookingApplication : lstLabBookingApplication) {
            if (mapLabBooking.get(objLabBookingApplication.BookedLab__c) != null) {
                LabBooking__c objLabBooking = mapLabBooking.get(objLabBookingApplication.BookedLab__c);
                objLabBookingApplication.X1stApprover__c = objLabBooking.X1stApprover__c;
            }
        }
    }
}