force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/TeachingSupplyBorrowingApplication__c.object-meta.xml
<CustomObject>
    <label>教学用品借用申请</label>
    <nameField>
        <displayFormat>TSBA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartDateAndTime__c</fullName>
    <inlineHelpText>按日期和节次借用时，此字段将在保存后自动计算，无需填写。</inlineHelpText>
    <label>借用开始时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/TeachingSupply__c.field-meta.xml
<CustomField>
    <fullName>TeachingSupply__c</fullName>
    <label>物品</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>TeachingSupplyGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/TeachingSupplyGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>话筒</fullName>
    </customValue>
    <customValue>
        <fullName>扩音器</fullName>
    </customValue>
    <customValue>
        <fullName>HDMI转VGA转换器</fullName>
    </customValue>
    <customValue>
        <fullName>网线</fullName>
    </customValue>
    <customValue>
        <fullName>百兆交换机(5口)</fullName>
    </customValue>
    <customValue>
        <fullName>录音机</fullName>
    </customValue>
    <customValue>
        <fullName>录像机</fullName>
    </customValue>
    <customValue>
        <fullName>万用表</fullName>
    </customValue>
    <customValue>
        <fullName>生物用显微镜</fullName>
    </customValue>
    <customValue>
        <fullName>秒表</fullName>
    </customValue>
    <customValue>
        <fullName>电焊机</fullName>
    </customValue>
    <customValue>
        <fullName>烧杯</fullName>
    </customValue>
    <customValue>
        <fullName>量筒</fullName>
    </customValue>
    <customValue>
        <fullName>乒乓球拍</fullName>
    </customValue>
    <customValue>
        <fullName>羽毛球拍</fullName>
    </customValue>
    <customValue>
        <fullName>足球</fullName>
    </customValue>
    <customValue>
        <fullName>篮球</fullName>
    </customValue>
    <masterLabel>教学用品</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RS_Dashboard_Ctl.cls
public with sharing class RS_Dashboard_Ctl {

    @AuraEnabled(cacheable = true)
    public static ResponseResult getTeachingSupplyEachTime(){
        List<AggregateResult> lstTeachingSupply = [
            SELECT 
                WEEK_IN_YEAR(BorrowingStartDateAndTime__c) week, TeachingSupply__c, SUM(Quantity__c) qty 
            FROM 
                TeachingSupplyBorrowingApplication__c 
            GROUP BY 
                WEEK_IN_YEAR(BorrowingStartDateAndTime__c), TeachingSupply__c 
            ORDER BY 
                WEEK_IN_YEAR(BorrowingStartDateAndTime__c) ASC 
        ];
        EchartWrapper objEchart = new EchartWrapper();
        Set<String> setXData = new Set<String>();
        Set<String> setLegend = new Set<String>();
        // 封装X轴坐标、图例
        for(AggregateResult objTeachingSupply : lstTeachingSupply){
            setXData.add(String.valueOf(objTeachingSupply.get('week')));
            setLegend.add(String.valueOf(objTeachingSupply.get('TeachingSupply__c')));
        }
        // 封装系列
        SeriesWrapper objSeries = new SeriesWrapper();
        objSeries.type = 'line';
        for(AggregateResult objTeachingSupply : lstTeachingSupply){
            objSeries.data.add(objTeachingSupply.get('qty'));
        }
        objEchart.series.add(objSeries);
        // 封装X轴参数
        objEchart.xAxis.type = 'category';
        objEchart.xAxis.data = new List<String>(setXData);
        ResponseResult objResponse = new ResponseResult();
        objResponse.status = 'OK';
        objResponse.data = objEchart;
        return objResponse;
    }

    public class EchartWrapper {
        @AuraEnabled public List<String> legend;
        @AuraEnabled public List<SeriesWrapper> series;
        @AuraEnabled public XAxisWrapper xAxis;

        public EchartWrapper(){
            this.series = new List<SeriesWrapper>();
            this.xAxis = new XAxisWrapper();
        }
    }

    public class SeriesWrapper {
        @AuraEnabled public String name;
        @AuraEnabled public String type;
        @AuraEnabled public String stack;
        @AuraEnabled public List<Object> data;

        public SeriesWrapper(){
            this.data = new List<Object>();
        }
    }

    public class XAxisWrapper {
        @AuraEnabled public String type;
        @AuraEnabled public String boundaryGap;
        @AuraEnabled public List<Object> data;

        public XAxisWrapper(){
            this.data = new List<Object>();
        }
    }

    public class ResponseResult {
        @AuraEnabled public String status;
        @AuraEnabled public String message;
        @AuraEnabled public Object data;
    }
}