force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Message</label>
    <length>16384</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/LogSubject__c.field-meta.xml
<CustomField>
    <fullName>LogSubject__c</fullName>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Reference__c.field-meta.xml
<CustomField>
    <fullName>Reference__c</fullName>
    <label>Reference</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RS_Logger_Cmn.cls
/**
 * @description 日志公共类
 * @author: AnonyEast
 * @date: 2023-01-07
 */
public without sharing class RS_Logger_Cmn {
    /**
     * @description 创建日志
     * @param strSubject: 日志主题
     * @param strMessage: 日志内容
     * @param strReference: 日志来源
     * @return void
     */
    public static void createLog(String strSubject,String strMessage,String strReference) {
        Log__c objLog = new Log__c(LogSubject__c = strSubject, LogMessage__c = strMessage, Reference__c = strReference);
        insert objLog;
    }

    /**
     * @description 创建异常日志
     * @param strSubject: 日志主题
     * @param objEx: 异常对象
     * @param strReference: 日志来源
     * @return void
     */
    public static void createLog(String strSubject,Exception objEx,String strReference) {
        String strExceptionMessage = objEx.getMessage();
        String strExceptionType = objEx.getTypeName();
        Integer strExceptionLine = objEx.getLineNumber();
        String strExceptionStackTrace = objEx.getStackTraceString();
        String strMessage = 'ExceptionMessage: ' + strExceptionMessage + '\n'
        + 'ExceptionType: ' + strExceptionType + '\n'
        + 'ExceptionLine: ' + strExceptionLine + '\n'
        + 'ExceptionStackTrace: \n' + strExceptionStackTrace;
        Log__c objLog = new Log__c(LogSubject__c = strSubject, LogMessage__c = strMessage, Reference__c = strReference);
        insert objLog;
    }
}