force-app/main/default/objects/Contact/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <label>班级</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CultureLevel__c.field-meta.xml
<CustomField>
    <fullName>CultureLevel__c</fullName>
    <label>文化程度</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EducationalSystem__c.field-meta.xml
<CustomField>
    <fullName>EducationalSystem__c</fullName>
    <label>学制</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>性别</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>男</fullName>
            </value>
            <value>
                <fullName>女</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>年级</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>专业</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessionGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SecondaryCollege__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollege__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>学生(学院)</relationshipLabel>
    <relationshipName>StuSecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StudentIdNumber__c.field-meta.xml
<CustomField>
    <fullName>StudentIdNumber__c</fullName>
    <label>身份证</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StudentNumber__c.field-meta.xml
<CustomField>
    <fullName>StudentNumber__c</fullName>
    <label>学号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StudentStatus__c.field-meta.xml
<CustomField>
    <fullName>StudentStatus__c</fullName>
    <label>学籍状态</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ProfessionGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>计算机科学与技术</fullName>
    </customValue>
    <customValue>
        <fullName>物联网工程</fullName>
    </customValue>
    <customValue>
        <fullName>计算机应用技术</fullName>
    </customValue>
    <customValue>
        <fullName>网络工程</fullName>
    </customValue>
    <customValue>
        <fullName>物流工程</fullName>
    </customValue>
    <customValue>
        <fullName>智能科学与技术</fullName>
    </customValue>
    <customValue>
        <fullName>软件工程</fullName>
    </customValue>
    <customValue>
        <fullName>体育教育</fullName>
    </customValue>
    <customValue>
        <fullName>社会体育指导与管理</fullName>
    </customValue>
    <customValue>
        <fullName>环境科学</fullName>
    </customValue>
    <customValue>
        <fullName>化学</fullName>
    </customValue>
    <customValue>
        <fullName>应用化学</fullName>
    </customValue>
    <customValue>
        <fullName>资源循环科学与工程</fullName>
    </customValue>
    <customValue>
        <fullName>化学类</fullName>
    </customValue>
    <customValue>
        <fullName>人文地理与城乡规划</fullName>
    </customValue>
    <customValue>
        <fullName>测绘工程</fullName>
    </customValue>
    <customValue>
        <fullName>地理科学</fullName>
    </customValue>
    <customValue>
        <fullName>商务英语</fullName>
    </customValue>
    <customValue>
        <fullName>翻译</fullName>
    </customValue>
    <customValue>
        <fullName>泰语</fullName>
    </customValue>
    <customValue>
        <fullName>英语</fullName>
    </customValue>
    <customValue>
        <fullName>外国语言文学类</fullName>
    </customValue>
    <customValue>
        <fullName>工程造价</fullName>
    </customValue>
    <customValue>
        <fullName>土木工程（留学生）</fullName>
    </customValue>
    <customValue>
        <fullName>土木工程</fullName>
    </customValue>
    <customValue>
        <fullName>视觉传达设计</fullName>
    </customValue>
    <customValue>
        <fullName>美术学</fullName>
    </customValue>
    <customValue>
        <fullName>产品设计</fullName>
    </customValue>
    <customValue>
        <fullName>动画</fullName>
    </customValue>
    <customValue>
        <fullName>环境设计</fullName>
    </customValue>
    <masterLabel>专业</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RS_SObjectUtil_Cmn.cls
/**
 * @description SObject工具类
 * @author: AnonyEast
 * @date: 2023-03-30
 */
public with sharing class RS_SObjectUtil_Cmn {
    /**
     * @description 获取用户对应的联系人信息和组织机构信息
     * @param setUserId 用户ID集合
     * 
     * @return lstUser 包含联系人字段、组织机构字段的用户对象列表
     */
    public static List<User> getUserDetailInfoList(Set<Id> setUserId) {
        List<User> lstUser = [
            SELECT 
                // 用户字段
                Id, Division, Department, Title, Address, Email, Phone, MobilePhone, ContactId, 
                // 学生所在组织机构字段(班级)
                Contact.Account.Id, Contact.Account.Name, Contact.Account.Owner.Id, Contact.Account.Owner.Name, Contact.Account.Owner.Email, 
                // 学生上级组织机构字段(二级学院)
                Contact.Account.Parent.Id, Contact.Account.Parent.Name, Contact.Account.Parent.Owner.Id, Contact.Account.Parent.Owner.Name, Contact.Account.Parent.Owner.Email, 
                // 学生字段
                Contact.Id, Contact.Name, Contact.Phone, Contact.Email, Contact.Title, Contact.Description, Contact.Grade__c, 
                Contact.ClassName__c, Contact.StudentNumber__c, Contact.SecondaryCollege__c, Contact.SecondaryCollege__r.Name, Contact.Profession__c, 
                Contact.Gender__c, Contact.StudentIdNumber__c, Contact.EducationalSystem__c, 
                Contact.CultureLevel__c, Contact.StudentStatus__c 
            FROM  
                User 
            WHERE 
                Id IN :setUserId 
        ];
        return lstUser;
    }

    public static Map<Id,User> getUserDetailInfoMap(Set<Id> setUserId) {
        return new Map<Id,User>(getUserDetailInfoList(setUserId));
    }

    @AuraEnabled(cacheable=true)
    public static User getUserDetailInfo(Id userId) {
        return getUserDetailInfoList(new Set<Id>{userId}).get(0);
    }

    /**
     * @description 获取学生对应的组织机构信息
     * @param setContactId 学生ID集合
     * 
     * @return lstContact 包含联系人字段、组织机构字段的联系人对象列表
     */
    public static List<Contact> getContactDetailInfoList(Set<Id> setContactId) {
        List<Contact> lstContact = [
            SELECT 
                // 学生字段
                Id, Name, Phone, Email, Title, Description, Grade__c, ClassName__c, StudentNumber__c, SecondaryCollege__c, SecondaryCollege__r.Name, Profession__c, 
                Gender__c, StudentIdNumber__c, EducationalSystem__c, CultureLevel__c, StudentStatus__c, 
                // 学生所在组织机构字段(班级)
                Account.Id, Account.Name, Account.Owner.Id, Account.Owner.Name, Account.Owner.Email, 
                // 学生上级组织机构字段(二级学院)
                Account.Parent.Id, Account.Parent.Name, Account.Parent.Owner.Id, Account.Parent.Owner.Name, Account.Parent.Owner.Email 
            FROM 
                Contact 
            WHERE 
                Id IN :setContactId 
        ];
        return lstContact;
    }

    public static Map<Id,Contact> getContactDetailInfoMap(Set<Id> setContactId) {
        return new Map<Id,Contact>(getContactDetailInfoList(setContactId));
    }

    public static Contact getContactDetailInfo(Id contactId) {
        return getContactDetailInfoList(new Set<Id>{contactId}).get(0);
    }

    /**
     * @description 二级学院ID映射
     * 
     * @return mapCollage
     */
    public static Map<Id,Account> getSecondryCollegeMap() {
        Map<Id,Account> mapSecondryCollage = new Map<Id,Account>([
            SELECT 
                Id, Name 
            FROM 
                Account 
            WHERE 
                Type = '教学科研单位' 
        ]);
        return mapSecondryCollage;
    }
}