force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>专业</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessionGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SecondaryCollege__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollege__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>学生(学院)</relationshipLabel>
    <relationshipName>StuSecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StudentNumber__c.field-meta.xml
<CustomField>
    <fullName>StudentNumber__c</fullName>
    <label>学号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/LabBooking__c.object-meta.xml
<CustomObject>
    <label>实验室预约</label>
    <nameField>
        <displayFormat>LB-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/LabBooking__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>取消勾选时，该实验室在学生门户将不可见，学生无法进行预约操作。</inlineHelpText>
    <label>可预约</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/BookedNumber__c.field-meta.xml
<CustomField>
    <fullName>BookedNumber__c</fullName>
    <label>已预约人数</label>
    <summaryFilterItems>
        <field>LabBookingApplication__c.ApprovalStatus__c</field>
        <operation>equals</operation>
        <value>审批中, 已批准</value>
    </summaryFilterItems>
    <summaryForeignKey>LabBookingApplication__c.BookedLab__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/BookingEndTime__c.field-meta.xml
<CustomField>
    <fullName>BookingEndTime__c</fullName>
    <label>停止预约时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/BookingStartTime__c.field-meta.xml
<CustomField>
    <fullName>BookingStartTime__c</fullName>
    <label>开放预约时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>容量</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/ClosingTime__c.field-meta.xml
<CustomField>
    <fullName>ClosingTime__c</fullName>
    <label>关闭时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/LabAddress__c.field-meta.xml
<CustomField>
    <fullName>LabAddress__c</fullName>
    <label>实验室地址</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/LabEquipment__c.field-meta.xml
<CustomField>
    <fullName>LabEquipment__c</fullName>
    <inlineHelpText>请输入实验室的可用设备或仪器，如计算机、投影仪、白板等。</inlineHelpText>
    <label>实验室设备</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/LabType__c.field-meta.xml
<CustomField>
    <fullName>LabType__c</fullName>
    <label>场地类别</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SiteTypeGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/OpeningTime__c.field-meta.xml
<CustomField>
    <fullName>OpeningTime__c</fullName>
    <label>开放时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LabBooking__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>仅在“需要批准”字段勾选时生效。</inlineHelpText>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LB1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/LabBookingApplication__c.object-meta.xml
<CustomObject>
    <label>实验室预约申请</label>
    <nameField>
        <displayFormat>LBA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LabBookingApplication__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>申请人</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>实验室预约申请</relationshipLabel>
    <relationshipName>LBAApplicant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>批准状态</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApprovalStatusGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/BookedLab__c.field-meta.xml
<CustomField>
    <fullName>BookedLab__c</fullName>
    <label>预约的实验室</label>
    <referenceTo>LabBooking__c</referenceTo>
    <relationshipLabel>预约申请</relationshipLabel>
    <relationshipName>LabBookingApplications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/BookingPeriod__c.field-meta.xml
<CustomField>
    <fullName>BookingPeriod__c</fullName>
    <formula>IF(
				ISBLANK(BookedLab__r.OpeningTime__c) &amp;&amp; ISBLANK(BookedLab__r.ClosingTime__c),
				&quot;&quot;,
				TEXT(YEAR(DATEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))) &amp; &quot;/&quot; &amp; 
				TEXT(MONTH(DATEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))) &amp; &quot;/&quot; &amp; 
				TEXT(DAY(DATEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))) &amp; &quot; &quot; &amp; 
				LPAD(TEXT(HOUR(TIMEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))),2,&apos;0&apos;) &amp; &quot;:&quot; &amp; 
				LPAD(TEXT(MINUTE(TIMEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))),2,&apos;0&apos;) &amp; &quot; - &quot; &amp; 
				TEXT(YEAR(DATEVALUE(BookedLab__r.ClosingTime__c + 8 / 24))) &amp; &quot;/&quot; &amp; 
				TEXT(MONTH(DATEVALUE(BookedLab__r.ClosingTime__c + 8 / 24))) &amp; &quot;/&quot; &amp; 
				TEXT(DAY(DATEVALUE(BookedLab__r.ClosingTime__c + 8 / 24))) &amp; &quot; &quot; &amp; 
				LPAD(TEXT(HOUR(TIMEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))),2,&apos;0&apos;) &amp; &quot;:&quot; &amp; 
				LPAD(TEXT(MINUTE(TIMEVALUE(BookedLab__r.OpeningTime__c + 8 / 24))),2,&apos;0&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>预约时段</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>班级</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>二级学院班级</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>实验室预约申请(班级维度)</relationshipLabel>
    <relationshipName>LBAClass</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/LabAddress__c.field-meta.xml
<CustomField>
    <fullName>LabAddress__c</fullName>
    <formula>BookedLab__r.LabAddress__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>实验室地址</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>CASE(
				TEXT(BookedLab__r.Location__c),
				&apos;MingdeBuilding&apos;,&apos;明德楼&apos;,
				&apos;BoyaBuilding&apos;,&apos;伯牙楼&apos;,
				&apos;HongwenBuilding&apos;,&apos;弘文楼&apos;,
				&apos;DaqianBuilding&apos;,&apos;大千楼&apos;,
				&apos;GezhiBuilding&apos;,&apos;格致楼&apos;,
				&apos;TrainingCenter&apos;,&apos;培训中心&apos;,
				&apos;X1stPracticalTrainingBuilding&apos;,&apos;第一实训楼&apos;,
				&apos;X2ndPracticalTrainingBuilding&apos;,&apos;第二实训楼&apos;,
				&apos;X3rdPracticalTrainingBuilding&apos;,&apos;第三实训楼&apos;,
				&apos;X1stPlayground&apos;,&apos;第一运动场&apos;,
				&apos;X2ndPlayground&apos;,&apos;第二运动场&apos;,
				&apos;X3rdPlayground&apos;,&apos;第三运动场&apos;,
				&apos;X4thPlayground&apos;,&apos;第四运动场&apos;,
				&apos;X5thPlayground&apos;,&apos;第五运动场&apos;,
				&apos;GroundTrackField&apos;,&apos;田径场&apos;,
				TEXT(BookedLab__r.Location__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>地点</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/SecondaryCollege__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollege__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>实验室预约申请(学院维度)</relationshipLabel>
    <relationshipName>LBASecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/StudentNumber__c.field-meta.xml
<CustomField>
    <fullName>StudentNumber__c</fullName>
    <label>学号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LabBookingApplication__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>此字段将在保存后自动从“预约的实验室”中的“审批人”字段取值，无需手动填写。</inlineHelpText>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LBA1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/ApprovalStatusGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Draft</fullName>
        <default>true</default>
        <label>草稿</label>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <label>审批中</label>
    </customValue>
    <customValue>
        <fullName>Approved</fullName>
        <label>已批准</label>
    </customValue>
    <customValue>
        <fullName>Rejected</fullName>
        <label>已拒绝</label>
    </customValue>
    <customValue>
        <fullName>Canceled</fullName>
        <label>已取消</label>
    </customValue>
    <masterLabel>批准状态</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProfessionGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>计算机科学与技术</fullName>
    </customValue>
    <customValue>
        <fullName>物联网工程</fullName>
    </customValue>
    <customValue>
        <fullName>计算机应用技术</fullName>
    </customValue>
    <customValue>
        <fullName>网络工程</fullName>
    </customValue>
    <customValue>
        <fullName>物流工程</fullName>
    </customValue>
    <customValue>
        <fullName>智能科学与技术</fullName>
    </customValue>
    <customValue>
        <fullName>软件工程</fullName>
    </customValue>
    <customValue>
        <fullName>体育教育</fullName>
    </customValue>
    <customValue>
        <fullName>社会体育指导与管理</fullName>
    </customValue>
    <customValue>
        <fullName>环境科学</fullName>
    </customValue>
    <customValue>
        <fullName>化学</fullName>
    </customValue>
    <customValue>
        <fullName>应用化学</fullName>
    </customValue>
    <customValue>
        <fullName>资源循环科学与工程</fullName>
    </customValue>
    <customValue>
        <fullName>化学类</fullName>
    </customValue>
    <customValue>
        <fullName>人文地理与城乡规划</fullName>
    </customValue>
    <customValue>
        <fullName>测绘工程</fullName>
    </customValue>
    <customValue>
        <fullName>地理科学</fullName>
    </customValue>
    <customValue>
        <fullName>商务英语</fullName>
    </customValue>
    <customValue>
        <fullName>翻译</fullName>
    </customValue>
    <customValue>
        <fullName>泰语</fullName>
    </customValue>
    <customValue>
        <fullName>英语</fullName>
    </customValue>
    <customValue>
        <fullName>外国语言文学类</fullName>
    </customValue>
    <customValue>
        <fullName>工程造价</fullName>
    </customValue>
    <customValue>
        <fullName>土木工程（留学生）</fullName>
    </customValue>
    <customValue>
        <fullName>土木工程</fullName>
    </customValue>
    <customValue>
        <fullName>视觉传达设计</fullName>
    </customValue>
    <customValue>
        <fullName>美术学</fullName>
    </customValue>
    <customValue>
        <fullName>产品设计</fullName>
    </customValue>
    <customValue>
        <fullName>动画</fullName>
    </customValue>
    <customValue>
        <fullName>环境设计</fullName>
    </customValue>
    <masterLabel>专业</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SiteTypeGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>专用机房</fullName>
    </customValue>
    <customValue>
        <fullName>智慧教室</fullName>
    </customValue>
    <customValue>
        <fullName>琴房</fullName>
    </customValue>
    <customValue>
        <fullName>普通教室</fullName>
    </customValue>
    <customValue>
        <fullName>舞蹈房</fullName>
    </customValue>
    <customValue>
        <fullName>室外篮球场</fullName>
    </customValue>
    <customValue>
        <fullName>多媒体教室</fullName>
    </customValue>
    <customValue>
        <fullName>录播教室</fullName>
    </customValue>
    <customValue>
        <fullName>机房</fullName>
    </customValue>
    <customValue>
        <fullName>实践基地</fullName>
    </customValue>
    <customValue>
        <fullName>普通（专用）</fullName>
    </customValue>
    <customValue>
        <fullName>资料室</fullName>
    </customValue>
    <customValue>
        <fullName>田径场</fullName>
    </customValue>
    <customValue>
        <fullName>实验室</fullName>
    </customValue>
    <customValue>
        <fullName>绘图室</fullName>
    </customValue>
    <customValue>
        <fullName>语音教室</fullName>
    </customValue>
    <customValue>
        <fullName>微格教室</fullName>
    </customValue>
    <customValue>
        <fullName>画室</fullName>
    </customValue>
    <customValue>
        <fullName>艺术类专用</fullName>
    </customValue>
    <customValue>
        <fullName>办公室</fullName>
    </customValue>
    <customValue>
        <fullName>实训室</fullName>
    </customValue>
    <customValue>
        <fullName>运动场</fullName>
    </customValue>
    <masterLabel>场地类别</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RS_LabBooking_Ctl.cls
/**
 * @description LabBooking Controller
 * @author AnonyEast
 * @date 2023-03-26
 */
public with sharing class RS_LabBooking_Ctl {
    private static String currentUserContactId = RS_SObjectUtil_Cmn.getUserDetailInfo(UserInfo.getUserId()).ContactId;

    /**
     * @description 获取可预约的实验室
     * 
     * @return lstRtnAvailableBooking 可预约的实验室列表
     */
    @AuraEnabled(cacheable=false)
    public static RS_ResponseResult getAvailableBooking(Integer intPageNum, Integer intPageSize, List<String> lstLocation, List<String> lstLabType 
                                                        ,List<String> lstApprovalStatus, String strLabEquipment, Boolean boolNoNeedApproval 
                                                        ,Date dtOpeningDate, Date dtClosingDate, Date dtBookingStartDate, Date dtBookingEndDate) {
        Integer totalCounts = 0;
        String strQuery = '';
        String strSubQuery = '';
        // 子查询：查询当前用户在各实验室提交的预约申请
        strSubQuery += 'SELECT ';
        strSubQuery +=     'Applicant__c, ApprovalStatus__c, CreatedDate ';
        strSubQuery += 'FROM ';
        strSubQuery +=     'LabBookingApplications__r ';
        strSubQuery += 'WHERE ';
        strSubQuery +=     'Applicant__c = \'' + currentUserContactId + '\' ';
        strSubQuery += 'ORDER BY ';
        strSubQuery +=     'CreatedDate DESC ';
        // 原始查询
        strQuery += 'SELECT ';
        strQuery +=     'Id, Location__c, LabAddress__c, LabType__c, LabEquipment__c ';
        strQuery +=     ', OpeningTime__c, ClosingTime__c, BookingStartTime__c, BookingEndTime__c ';
        strQuery +=     ', Capacity__c, BookedNumber__c, Active__c, X1stApprover__c, X1stApprover__r.Name ';
        strQuery +=     ', (' + strSubQuery + ') ';
        strQuery += 'FROM ';
        strQuery +=     'LabBooking__c ';
        strQuery += 'WHERE ';
        strQuery +=     'Active__c = true ';
        // 筛选条件
        if (lstLocation != null && lstLocation.size() > 0) {
            strQuery += 'AND Location__c IN :lstLocation ';
        }
        if (lstLabType != null && lstLabType.size() > 0) {
            strQuery += 'AND LabType__c IN :lstLabType ';
        }
        if (strLabEquipment != null && strLabEquipment.length() > 0) {
            strQuery += 'AND LabEquipment__c LIKE \'%' + strLabEquipment + '%\' ';
        }
        if (boolNoNeedApproval != null && boolNoNeedApproval == true) {
            strQuery += 'AND X1stApprover__c = null ';
        }
        if (dtOpeningDate != null) {
            Datetime dtOpeningDatetime = RS_ApexUtil_Cmn.localDateToGmtDatetime(dtOpeningDate);
            strQuery += 'AND OpeningTime__c >= :dtOpeningDatetime ';
        }
        if (dtClosingDate != null) {
            Datetime dtClosingDatetime = RS_ApexUtil_Cmn.localDateToGmtDatetime(dtClosingDate);
            strQuery += 'AND ClosingTime__c <= :dtClosingDatetime ';
        }
        if (dtBookingStartDate != null) {
            Datetime dtBookingStartDatetime = RS_ApexUtil_Cmn.localDateToGmtDatetime(dtBookingStartDate);
            strQuery += 'AND BookingStartTime__c >= :dtBookingStartDatetime ';
        }
        if (dtBookingEndDate != null) {
            Datetime dtBookingEndDatetime = RS_ApexUtil_Cmn.localDateToGmtDatetime(dtBookingEndDate);
            strQuery += 'AND BookingEndTime__c <= :dtBookingEndDatetime ';
        }
        if (lstApprovalStatus != null && lstApprovalStatus.size() > 0) {
            strQuery += 'AND LabBookingApplications__r.ApprovalStatus__c IN :lstApprovalStatus ';
        }
        strQuery += 'ORDER BY ';
        strQuery +=     'OpeningTime__c DESC NULLS LAST ';
        // 不带分页的SOQL语句
        String strQueryWithoutPagination = strQuery;
        // 添加分页
        if (intPageNum != null && intPageSize != null) {
            Integer intOffset = (intPageNum - 1) * intPageSize;
            strQuery += ' LIMIT :intPageSize OFFSET :intOffset ';
        }
        // 未分页查询
        List<LabBooking__c> lstAvailableBooking = Database.query(strQueryWithoutPagination);
        totalCounts = lstAvailableBooking.size();
        // 分页查询
        lstAvailableBooking = Database.query(strQuery);
        // 自定义封装
        Map<Id,AvailableBookingWrapper> mapAvailableBookingWrapper = new Map<Id,AvailableBookingWrapper>();
        // 存储当前用户预约状态
        for(LabBooking__c objAvailableBooking : lstAvailableBooking){
            for(LabBookingApplication__c objApplication : objAvailableBooking.LabBookingApplications__r){
                AvailableBookingWrapper objAvailableBookingWrapper = new AvailableBookingWrapper();
                objAvailableBookingWrapper.userBookingStatus = objApplication.ApprovalStatus__c;
                mapAvailableBookingWrapper.put(objAvailableBooking.Id, objAvailableBookingWrapper);
                break;
            }
        }
        // 转换为Map
        List<Map<String, Object>> lstRtnAvailableBooking = RS_ApexUtil_Cmn.objectToMap(lstAvailableBooking);

        // 封装返回体
        Map<String, Object> mapLocationPicklistDescribe = RS_ApexUtil_Cmn.getPicklistDescribe('LabBooking__c', 'Location__c');
        for(Map<String, Object> mapAvailableBooking : lstRtnAvailableBooking){
            // API Name转Label
            mapAvailableBooking.put('Location__c',RS_ApexUtil_Cmn.picklistValueToLabel((String)mapAvailableBooking.get('Location__c'), mapLocationPicklistDescribe));
            mapAvailableBooking.put('CardTitle',mapAvailableBooking.get('Location__c') + ' ' + mapAvailableBooking.get('LabAddress__c'));
            // 当前用户预约状态
            AvailableBookingWrapper objAvailableBookingWrapper = mapAvailableBookingWrapper.get((String)mapAvailableBooking.get('Id'));
            if(objAvailableBookingWrapper != null){
                mapAvailableBooking.put('userBookingStatus',objAvailableBookingWrapper.userBookingStatus);
            }
        }
        return new RS_ResponseResult(RS_Constants.RTN_KEY_OK,lstRtnAvailableBooking,totalCounts);
    }

    /**
     * @description 获取当前用户预约的实验室
     * 
     * @return lstRtnMyBooking 当前用户预约的实验室列表
     */
    @AuraEnabled(cacheable=false)
    public static RS_ResponseResult getMyBooking(Integer intPageNum, Integer intPageSize) {
        Integer totalCounts = 0;
        String strQuery = '';
        strQuery += 'SELECT ';
        strQuery +=     'Id, CreatedById, BookedLab__c, ';
        strQuery +=     'Applicant__c, Applicant__r.Name, StudentNumber__c, SecondaryCollege__c, SecondaryCollege__r.Name, Major__c, Class__c, Class__r.Name, ';
        strQuery +=     'Location__c, LabAddress__c, BookingPeriod__c, ';
        strQuery +=     'ApprovalStatus__c, X1stApprover__c, X1stApprover__r.Name, FORMAT(CreatedDate), FORMAT(LastModifiedDate) ';
        strQuery += 'FROM ';
        strQuery +=     'LabBookingApplication__c ';
        strQuery += 'WHERE ';
        strQuery +=     'Applicant__c = \'' + currentUserContactId + '\' ';
        strQuery += 'ORDER BY ';
        strQuery +=     'LastModifiedDate DESC';
        // 不带分页的SOQL语句
        String strQueryWithoutPagination = strQuery;
        // 添加分页
        if (intPageNum != null && intPageSize != null) {
            Integer intOffset = (intPageNum - 1) * intPageSize;
            strQuery += ' LIMIT :intPageSize OFFSET :intOffset ';
        }
        // 未分页查询
        List<LabBookingApplication__c> lstMyBooking = Database.query(strQueryWithoutPagination);
        totalCounts = lstMyBooking.size();
        // 分页查询
        lstMyBooking = Database.query(strQuery);
        // 转换为Map
        List<Map<String, Object>> lstRtnMyBooking = RS_ApexUtil_Cmn.objectToMap(lstMyBooking);
        // 封装返回体
        Map<String, Object> mapLocationPicklistDescribe = RS_ApexUtil_Cmn.getPicklistDescribe('LabBookingApplication__c', 'Location__c');
        Map<String, Object> mapApprovalStatusPicklistDescribe = RS_ApexUtil_Cmn.getPicklistDescribe('LabBookingApplication__c', 'ApprovalStatus__c');
        for(Map<String, Object> mapMyBooking : lstRtnMyBooking){
            // API Name -> Label
            mapMyBooking.put('Location__c',RS_ApexUtil_Cmn.picklistValueToLabel((String)mapMyBooking.get('Location__c'), mapLocationPicklistDescribe));
            mapMyBooking.put('ApprovalStatus__c',RS_ApexUtil_Cmn.picklistValueToLabel((String)mapMyBooking.get('ApprovalStatus__c'), mapApprovalStatusPicklistDescribe));
            // 是否可取消预约
            if (mapMyBooking.get('ApprovalStatus__c') == RS_Constants.PICKLIST_APPROVAL_STATUS_CANCELED_LABEL || mapMyBooking.get('ApprovalStatus__c') == RS_Constants.PICKLIST_APPROVAL_STATUS_REJECTED_LABEL) {
                mapMyBooking.put('isDisabledCancelBooking',true);
            }else{
                mapMyBooking.put('isDisabledCancelBooking',false);
            }
        }
        return new RS_ResponseResult(RS_Constants.RTN_KEY_OK,lstRtnMyBooking,totalCounts);
    }

    /**
     * @description 用户预约请求
     * @param labBookingId 实验室预约Id
     * 
     * @return 
     */
    @AuraEnabled(cacheable=false)
    public static RS_ResponseResult bookingRequest(Id labBookingId) {
        Id currentUserId = UserInfo.getUserId();
        // 检查是否可以预约
        Map<String,Object> mapCheckResult = checkBooking(labBookingId,currentUserId);
        if ((Boolean)mapCheckResult.get('isBookable')) {
            // 执行预约操作
            return executeBookingAction(labBookingId,currentUserId);
        }else{
            return new RS_ResponseResult(RS_Constants.RTN_KEY_NG, (String)mapCheckResult.get('message'));
        }
    }

    /**
     * @description 检查用户是否可以预约当前实验室
     * @param labBookingId 实验室预约Id
     * @param userId 用户Id
     * 
     * @return RS_ResponseResult
     */
    public static Map<String,Object> checkBooking(Id labBookingId, Id userId) {
        Map<String,Object> mapCheckResult = new Map<String,Object>();
        // 检查同一个可预约实验室是否有审批中、已批准的预约申请
        List<LabBookingApplication__c> lstBookingApplication = [
            SELECT 
                Id 
            FROM 
                LabBookingApplication__c 
            WHERE 
                BookedLab__c = :labBookingId 
                AND CreatedById = :userId 
                AND ApprovalStatus__c IN (:RS_Constants.PICKLIST_APPROVAL_STATUS_PENDING, :RS_Constants.PICKLIST_APPROVAL_STATUS_APPROVED)
        ];
        if (lstBookingApplication != null && lstBookingApplication.size() > 0) {
            mapCheckResult.put('isBookable',false);
            mapCheckResult.put('message','你选择的实验室已存在审批中/已批准的预约申请。');
            return mapCheckResult;
        }
        // 检查当前时间是否在开放预约时间、是否约满
        LabBooking__c objLabBooking = [
            SELECT 
                Id,	BookingStartTime__c, BookingEndTime__c, ClosingTime__c, BookedNumber__c, Capacity__c 
            FROM 
                LabBooking__c 
            WHERE 
                Id = :labBookingId 
        ];
        // 是否在开放预约时间
        Datetime datetimeNow = Datetime.now();
        if (datetimeNow > objLabBooking.ClosingTime__c) {
            mapCheckResult.put('isBookable',false);
            mapCheckResult.put('message','你选择的实验室已超过开放时间段。');
            return mapCheckResult;
        }else if(datetimeNow < objLabBooking.BookingStartTime__c){
            mapCheckResult.put('isBookable',false);
            mapCheckResult.put('message','你选择的实验室暂未开始预约。');
            return mapCheckResult;
        }else if(datetimeNow > objLabBooking.BookingEndTime__c){
            mapCheckResult.put('isBookable',false);
            mapCheckResult.put('message','你选择的实验室已超过可预约时间段。');
            return mapCheckResult;
        }
        // 是否禁止预约
        if (objLabBooking.BookedNumber__c >= objLabBooking.Capacity__c) {
            mapCheckResult.put('isBookable',false);
            mapCheckResult.put('message','你选择的实验室预约人数已满');
            return mapCheckResult;
        }
        mapCheckResult.put('isBookable',true);
        return mapCheckResult;
    }

    /**
     * @description 执行预约操作
     * @param labBookingId 实验室预约Id
     * @param userId 用户Id
     * 
     * @return RS_ResponseResult
     */
    public static RS_ResponseResult executeBookingAction(Id labBookingId, Id userId) {
        // 获取用户详细信息
        User userDetailInfo = RS_SObjectUtil_Cmn.getUserDetailInfo(userId);
        LabBookingApplication__c objBookingApplication = new LabBookingApplication__c();
        objBookingApplication.BookedLab__c = labBookingId;
        objBookingApplication.Applicant__c = userDetailInfo.ContactId;
        objBookingApplication.StudentNumber__c = userDetailInfo.Contact.StudentNumber__c;
        objBookingApplication.SecondaryCollege__c = userDetailInfo.Contact.SecondaryCollege__c;
        objBookingApplication.Major__c = userDetailInfo.Contact.Profession__c;
        objBookingApplication.Class__c = userDetailInfo.Contact.Account.Id;
        // 设置回滚点
        System.Savepoint objBeforeInsertSavePoint = Database.setSavepoint();
        // 插入数据库
        Database.SaveResult insertResult = Database.insert(objBookingApplication);
        // 插入成功
        if (insertResult.isSuccess()) {
            // 提交待审批
            RS_ResponseResult objResponseResult = submitApprovalProcess(objBookingApplication.Id,userId);
            // 批准过程提交成功
            if (objResponseResult.status == RS_Constants.RTN_KEY_OK) {
                List<LabBookingApplication__c> lstBookingApplication = new List<LabBookingApplication__c>{objBookingApplication};
                objResponseResult.data = RS_ApexUtil_Cmn.objectToMap(lstBookingApplication);
                return objResponseResult;
            // 批准过程提交失败
            }else{
                // 回滚
                Database.rollback(objBeforeInsertSavePoint);
                return objResponseResult;
            }
        // 插入失败
        }else{
            String strErrorMessage = '';
            Database.Error[] lstErrorInfo = insertResult.getErrors();
            for (Database.Error errorInfo : lstErrorInfo) {
                strErrorMessage = errorInfo.getStatusCode() + ': ' + errorInfo.getMessage() + '\n';
            }
            return new RS_ResponseResult(RS_Constants.RTN_KEY_NG, strErrorMessage);
        }
    }

    /**
     * @description 提交待审批
     * @param labBookingApplicationId 实验室预约申请Id
     * 
     * @return RS_ResponseResult
     */
    public static RS_ResponseResult submitApprovalProcess(Id labBookingApplicationId, Id userId) {
        // 创建ProcessSubmitRequest实例
        Approval.ProcessSubmitRequest objApprovalSubmitRequest = new Approval.ProcessSubmitRequest();
        objApprovalSubmitRequest.setComments('申请人发起预约申请，系统自动提交审批。');
        objApprovalSubmitRequest.setSubmitterId(userId);
        objApprovalSubmitRequest.setObjectId(labBookingApplicationId);
        // 提交审批
        Approval.ProcessResult objApprovalSubmitResult = Approval.process(objApprovalSubmitRequest);
        if (objApprovalSubmitResult.isSuccess()) {
            return new RS_ResponseResult(RS_Constants.RTN_KEY_OK);
        }else{
            String strErrorMessage = '';
            Database.Error[] lstErrorInfo = objApprovalSubmitResult.getErrors();
            for (Database.Error errorInfo : lstErrorInfo) {
                strErrorMessage = errorInfo.getStatusCode() + ': ' + errorInfo.getMessage() + '\n';
            }
            return new RS_ResponseResult(RS_Constants.RTN_KEY_NG, strErrorMessage);
        }
    }

    /**
     * @description 用户取消预约
     * @param labBookingApplicationId 实验室预约申请Id
     * 
     * @return RS_ResponseResult
     */
    @AuraEnabled(cacheable=false)
    public static RS_ResponseResult cancelBookingRequest(Id labBookingApplicationId) {
        LabBookingApplication__c objLabBookingApplication = [
            SELECT 
                Id, ApprovalStatus__c
            FROM 
                LabBookingApplication__c
            WHERE 
                Id = :labBookingApplicationId
            LIMIT 1
        ];
        // 批准状态: 审批中
        if (objLabBookingApplication.ApprovalStatus__c == RS_Constants.PICKLIST_APPROVAL_STATUS_PENDING) {
            // 撤回批准请求
            ProcessInstanceWorkitem objLabBookingApprovalWorkitem = RS_ApprovalProcess_Cmn.getProcessInstanceWorkitem(labBookingApplicationId);
            Approval.ProcessWorkitemRequest objApprovalWorkitemRequest = new Approval.ProcessWorkitemRequest();
            objApprovalWorkitemRequest.setWorkitemId(objLabBookingApprovalWorkitem.Id);
            objApprovalWorkitemRequest.setComments('申请人取消预约，系统自动撤回审批。');
            objApprovalWorkitemRequest.setAction(RS_Constants.APPROVAL_ACTION_RECALL);
            Approval.ProcessResult objApprovalWorkitemResult = Approval.process(objApprovalWorkitemRequest);
            if (objApprovalWorkitemResult.isSuccess()) {
                return new RS_ResponseResult(RS_Constants.RTN_KEY_OK);
            }else{
                String strErrorMessage = '';
                Database.Error[] lstErrorInfo = objApprovalWorkitemResult.getErrors();
                for (Database.Error errorInfo : lstErrorInfo) {
                    strErrorMessage = errorInfo.getStatusCode() + ': ' + errorInfo.getMessage() + '\n';
                }
                return new RS_ResponseResult(RS_Constants.RTN_KEY_NG, strErrorMessage);
            }
        // 批准状态: 已批准
        }else if(objLabBookingApplication.ApprovalStatus__c == RS_Constants.PICKLIST_APPROVAL_STATUS_APPROVED){
            objLabBookingApplication.ApprovalStatus__c = RS_Constants.PICKLIST_APPROVAL_STATUS_CANCELED;
            Database.SaveResult updateResult = Database.update(objLabBookingApplication);
            if (updateResult.isSuccess()) {
                return new RS_ResponseResult(RS_Constants.RTN_KEY_OK);
            }else{
                String strErrorMessage = '';
                Database.Error[] lstErrorInfo = updateResult.getErrors();
                for (Database.Error errorInfo : lstErrorInfo) {
                    strErrorMessage = errorInfo.getStatusCode() + ': ' + errorInfo.getMessage() + '\n';
                }
                return new RS_ResponseResult(RS_Constants.RTN_KEY_NG, strErrorMessage);
            }
        }else{
            return new RS_ResponseResult(RS_Constants.RTN_KEY_NG,'仅批准状态为审批中/已批准的预约申请可以取消预约。');
        }
    }

    /**
     * @description 获取当前实验室申请记录的最新批准步骤节点
     * 
     * @return lstApprovalStepDetail 批准节点列表
     */
    @AuraEnabled(cacheable=false)
    public static RS_ResponseResult getApprovalSteps(Id labApplicationId){
        return new RS_ResponseResult(RS_Constants.RTN_KEY_OK,RS_ApexUtil_Cmn.objectToMap(RS_ApprovalProcess_Cmn.getLatestApprovalNodes(labApplicationId)));
    }

    // 可预约实验室自定义封装
    public class AvailableBookingWrapper{
        public LabBooking__c objLabBooking {get; set;}
        public String userBookingStatus;
    }
}