force-app/main/default/objects/ApproverMapping__c/ApproverMapping__c.object-meta.xml
<CustomObject>
    <label>审批人Mapping</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApproverMapping__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>审批人</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Approver</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApproverMapping__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>部门</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApproverMapping__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>业务</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OperationGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Profession__c.field-meta.xml
<CustomField>
    <fullName>Profession__c</fullName>
    <label>专业</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProfessionGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SecondaryCollege__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollege__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>学生(学院)</relationshipLabel>
    <relationshipName>StuSecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/StudentNumber__c.field-meta.xml
<CustomField>
    <fullName>StudentNumber__c</fullName>
    <label>学号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/LeaveApplication__c.object-meta.xml
<CustomObject>
    <label>请假申请</label>
    <nameField>
        <displayFormat>LA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LeaveApplication__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>班级</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>二级学院班级</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>请假申请(班级维度)</relationshipLabel>
    <relationshipName>LAClass</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <label>专业</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/fields/SecondaryCollege__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollege__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>请假申请(学院维度)</relationshipLabel>
    <relationshipName>LASecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学生</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>请假申请</relationshipLabel>
    <relationshipName>LAStudent</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/fields/X1stApprover__c.field-meta.xml
<CustomField>
    <fullName>X1stApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>请假小于3天，需要班主任审批。此字段保存后自动赋值，无需手动填写。</inlineHelpText>
    <label>班主任审批</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LA1stApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/fields/X2ndApprover__c.field-meta.xml
<CustomField>
    <fullName>X2ndApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>请假3-7天，需要班主任、二级学院书记审批。此字段保存后自动赋值，无需手动填写。</inlineHelpText>
    <label>二级学院审批</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LA2ndApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LeaveApplication__c/fields/X3rdApprover__c.field-meta.xml
<CustomField>
    <fullName>X3rdApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>请假大于7天，需要班主任、二级学院书记、教务处审批。此字段保存后自动赋值，无需手动填写。</inlineHelpText>
    <label>教务处审批</label>
    <referenceTo>User</referenceTo>
    <relationshipName>LA3rdApprover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/OperationGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>TeachingSupplyBorrowing</fullName>
        <label>教学用品借用</label>
    </customValue>
    <customValue>
        <fullName>Leave</fullName>
        <label>请假</label>
    </customValue>
    <customValue>
        <fullName>LabBooking</fullName>
        <label>实验室预约</label>
    </customValue>
    <masterLabel>系统业务</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/ProfessionGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>计算机科学与技术</fullName>
    </customValue>
    <customValue>
        <fullName>物联网工程</fullName>
    </customValue>
    <customValue>
        <fullName>计算机应用技术</fullName>
    </customValue>
    <customValue>
        <fullName>网络工程</fullName>
    </customValue>
    <customValue>
        <fullName>物流工程</fullName>
    </customValue>
    <customValue>
        <fullName>智能科学与技术</fullName>
    </customValue>
    <customValue>
        <fullName>软件工程</fullName>
    </customValue>
    <customValue>
        <fullName>体育教育</fullName>
    </customValue>
    <customValue>
        <fullName>社会体育指导与管理</fullName>
    </customValue>
    <customValue>
        <fullName>环境科学</fullName>
    </customValue>
    <customValue>
        <fullName>化学</fullName>
    </customValue>
    <customValue>
        <fullName>应用化学</fullName>
    </customValue>
    <customValue>
        <fullName>资源循环科学与工程</fullName>
    </customValue>
    <customValue>
        <fullName>化学类</fullName>
    </customValue>
    <customValue>
        <fullName>人文地理与城乡规划</fullName>
    </customValue>
    <customValue>
        <fullName>测绘工程</fullName>
    </customValue>
    <customValue>
        <fullName>地理科学</fullName>
    </customValue>
    <customValue>
        <fullName>商务英语</fullName>
    </customValue>
    <customValue>
        <fullName>翻译</fullName>
    </customValue>
    <customValue>
        <fullName>泰语</fullName>
    </customValue>
    <customValue>
        <fullName>英语</fullName>
    </customValue>
    <customValue>
        <fullName>外国语言文学类</fullName>
    </customValue>
    <customValue>
        <fullName>工程造价</fullName>
    </customValue>
    <customValue>
        <fullName>土木工程（留学生）</fullName>
    </customValue>
    <customValue>
        <fullName>土木工程</fullName>
    </customValue>
    <customValue>
        <fullName>视觉传达设计</fullName>
    </customValue>
    <customValue>
        <fullName>美术学</fullName>
    </customValue>
    <customValue>
        <fullName>产品设计</fullName>
    </customValue>
    <customValue>
        <fullName>动画</fullName>
    </customValue>
    <customValue>
        <fullName>环境设计</fullName>
    </customValue>
    <masterLabel>专业</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RS_Leave_Before_Hdl.cls
/**
 * @description: LeaveApplication__c BeforeInsert, BeforeUpdate trigger handler
 * @author: AnonyEast
 * @date: 2023-04-08
 */
public with sharing class RS_Leave_Before_Hdl implements Triggers.Handler{
    public void handle() {
        try {
            // 更新后的对象
            List<LeaveApplication__c> lstNewLeaveApplication = (List<LeaveApplication__c>)Trigger.new;
            // 更新前的对象
            Map<Id, LeaveApplication__c> mapOldLeaveApplication = (Map<Id, LeaveApplication__c>)Trigger.oldMap;
            // 学生信息赋值、审批人赋值
            setStudentInfoAndApprover(lstNewLeaveApplication);
        } catch (Exception ex) {
            RS_Logger_Cmn.createLog('Leave_BeforeTrg_Exception',ex,'RS_Leave_Before_Hdl.handle');
        }
    }

    /**
     * @description 学生信息赋值、审批人赋值
     * @param lstLeaveApplication 请假申请列表
     */
    public static void setStudentInfoAndApprover(List<LeaveApplication__c> lstLeaveApplication) {
        // 存储OwnerId
        Set<Id> setRecordOwnerId = new Set<Id>();
        // 存储学生Id
        Set<Id> setRecordStudentId = new Set<Id>();
        for (LeaveApplication__c objLeave : lstLeaveApplication) {
            setRecordOwnerId.add(objLeave.OwnerId);
            if (objLeave.Student__c != null){
                setRecordStudentId.add(objLeave.Student__c);
            }
        }
        // 获取Owner的详细信息
        Map<Id,User> mapRecordOwner = RS_SObjectUtil_Cmn.getUserDetailInfoMap(setRecordOwnerId);
        // 获取学生的详细信息
        Map<Id,Contact> mapRecordStudent;
        if (setRecordStudentId.size() > 0) {
            mapRecordStudent = RS_SObjectUtil_Cmn.getContactDetailInfoMap(setRecordStudentId);
        }
        // 获取第三审批人(教务处)
        List<ApproverMapping__c> lstApproverMapping = [
            SELECT 
                Approver__c 
            FROM 
                ApproverMapping__c 
            WHERE 
                Department__c = '教务处' 
                AND Operation__c INCLUDES (:RS_Constants.PICKLIST_OPERATION_LEAVE) 
        ];
        // 学生信息相关字段赋值
        for (LeaveApplication__c objLeave : lstLeaveApplication) {
            // 记录类型：学生请假
            if (objLeave.RecordTypeId == RS_Constants.STUDENT_LEAVE_RECORD_TYPE_ID && mapRecordOwner.get(objLeave.OwnerId) != null) {
                // 学生字段有值时(内部提交)
                if (objLeave.Student__c != null) {
                    Contact objContact = mapRecordStudent.get(objLeave.Student__c);
                    objLeave.StudentNumber__c = objContact.StudentNumber__c;
                    objLeave.Class__c = objContact.Account.Id;
                    objLeave.SecondaryCollege__c = objContact.SecondaryCollege__c;
                    objLeave.Major__c = objContact.Profession__c;
                    // 第一审批人赋值(班主任)
                    objLeave.X1stApprover__c = objContact.Account.Owner.Id;
                    // 第二审批人赋值(二级学院书记)
                    objLeave.X2ndApprover__c = objContact.Account.Parent.Owner.Id;
                }
                // 学生字段值为空时(外部提交)
                if (objLeave.Student__c == null) {
                    User objOwner = mapRecordOwner.get(objLeave.OwnerId);
                    objLeave.Student__c = objOwner.ContactId;
                    objLeave.StudentNumber__c = objOwner.Contact.StudentNumber__c;
                    objLeave.Class__c = objOwner.Contact.Account.Id;
                    objLeave.SecondaryCollege__c = objOwner.Contact.SecondaryCollege__c;
                    objLeave.Major__c = objOwner.Contact.Profession__c;
                    // 第一审批人赋值(班主任)
                    objLeave.X1stApprover__c = objOwner.Contact.Account.Owner.Id;
                    // 第二审批人赋值(二级学院书记)
                    objLeave.X2ndApprover__c = objOwner.Contact.Account.Parent.Owner.Id;
                }
                // 第三审批人赋值(教务处)
                if (lstApproverMapping != null && lstApproverMapping.size() > 0) {
                    objLeave.X3rdApprover__c = lstApproverMapping.get(0).Approver__c;
                }
            }
        }
    }
}