force-app/main/default/objects/ClassTimesSchedule__mdt/ClassTimesSchedule__mdt.object-meta.xml
<CustomObject>
    <description>存储节次与上课时间、下课时间的映射。</description>
    <label>节次时间表</label>
</CustomObject>

force-app/main/default/objects/ClassTimesSchedule__mdt/fields/ClassEndTime__c.field-meta.xml
<CustomField>
    <fullName>ClassEndTime__c</fullName>
    <inlineHelpText>请严格按照mm:ss格式输入数据，例如：00:30,06:40,17:05,23:00</inlineHelpText>
    <label>下课时间</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassTimesSchedule__mdt/fields/ClassStartTime__c.field-meta.xml
<CustomField>
    <fullName>ClassStartTime__c</fullName>
    <inlineHelpText>请严格按照mm:ss格式输入数据，例如：00:30,06:40,17:05,23:00</inlineHelpText>
    <label>上课时间</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClassTimesSchedule__mdt/fields/ClassTimes__c.field-meta.xml
<CustomField>
    <fullName>ClassTimes__c</fullName>
    <label>节次</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/TeachingSupplyBorrowingApplication__c.object-meta.xml
<CustomObject>
    <label>教学用品借用申请</label>
    <nameField>
        <displayFormat>TSBA-{000000}</displayFormat>
        <label>序号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingEndClassTimes__c.field-meta.xml
<CustomField>
    <fullName>BorrowingEndClassTimes__c</fullName>
    <label>借用结束节次</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassTimesGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingEndDate__c.field-meta.xml
<CustomField>
    <fullName>BorrowingEndDate__c</fullName>
    <label>借用结束日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingEndDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>BorrowingEndDateAndTime__c</fullName>
    <inlineHelpText>按日期和节次借用时，此字段将在保存后自动计算，无需填写。</inlineHelpText>
    <label>借用结束时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartClassTimes__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartClassTimes__c</fullName>
    <label>借用开始节次</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ClassTimesGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartDate__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartDate__c</fullName>
    <label>借用开始日期</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/BorrowingStartDateAndTime__c.field-meta.xml
<CustomField>
    <fullName>BorrowingStartDateAndTime__c</fullName>
    <inlineHelpText>按日期和节次借用时，此字段将在保存后自动计算，无需填写。</inlineHelpText>
    <label>借用开始时间</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>地点</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TeachingLocationGlobal</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReceiveAddress__c.field-meta.xml
<CustomField>
    <fullName>ReceiveAddress__c</fullName>
    <inlineHelpText>领取地址会在审批通过后显示，无需填写。</inlineHelpText>
    <label>领取地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReceiveContact__c.field-meta.xml
<CustomField>
    <fullName>ReceiveContact__c</fullName>
    <inlineHelpText>领取联系人会在审批通过后显示，无需填写。</inlineHelpText>
    <label>领取联系人</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReceiveContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ReceiveContactPhone__c</fullName>
    <inlineHelpText>领取联系方式会在审批通过后显示，无需填写。</inlineHelpText>
    <label>领取联系方式</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReturnAddress__c.field-meta.xml
<CustomField>
    <fullName>ReturnAddress__c</fullName>
    <inlineHelpText>归还地址会在审批通过后显示，无需填写。</inlineHelpText>
    <label>归还地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReturnContact__c.field-meta.xml
<CustomField>
    <fullName>ReturnContact__c</fullName>
    <inlineHelpText>归还联系人会在审批通过后显示，无需填写。</inlineHelpText>
    <label>归还联系人</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/ReturnContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ReturnContactPhone__c</fullName>
    <inlineHelpText>归还联系方式会在审批通过后显示，无需填写。</inlineHelpText>
    <label>归还联系方式</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyBorrowingApplication__c/fields/SecondaryCollegeLookup__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollegeLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>学院</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>教学科研单位</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>教学用品借用申请(学院维度)</relationshipLabel>
    <relationshipName>TSBASecondaryCollege</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/TeachingSupplyReceiveAndReutrnContact__mdt.object-meta.xml
<CustomObject>
    <description>存储各教学地点的教学物品领取和归还的联系人信息。</description>
    <label>教学用品领取归还联系信息</label>
</CustomObject>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>启用</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>地点</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MingdeBuilding</fullName>
                <label>明德楼</label>
            </value>
            <value>
                <fullName>BoyaBuilding</fullName>
                <label>伯牙楼</label>
            </value>
            <value>
                <fullName>HongwenBuilding</fullName>
                <label>弘文楼</label>
            </value>
            <value>
                <fullName>DaqianBuilding</fullName>
                <label>大千楼</label>
            </value>
            <value>
                <fullName>GezhiBuilding</fullName>
                <label>格致楼</label>
            </value>
            <value>
                <fullName>TrainingCenter</fullName>
                <label>培训中心</label>
            </value>
            <value>
                <fullName>X1stPracticalTrainingBuilding</fullName>
                <label>第一实训楼</label>
            </value>
            <value>
                <fullName>X2ndPracticalTrainingBuilding</fullName>
                <label>第二实训楼</label>
            </value>
            <value>
                <fullName>X3rdPracticalTrainingBuilding</fullName>
                <label>第三实训楼</label>
            </value>
            <value>
                <fullName>X1stPlayground</fullName>
                <label>第一运动场</label>
            </value>
            <value>
                <fullName>X2ndPlayground</fullName>
                <label>第二运动场</label>
            </value>
            <value>
                <fullName>X3rdPlayground</fullName>
                <label>第三运动场</label>
            </value>
            <value>
                <fullName>X4thPlayground</fullName>
                <label>第四运动场</label>
            </value>
            <value>
                <fullName>X5thPlayground</fullName>
                <label>第五运动场</label>
            </value>
            <value>
                <fullName>GroundTrackField</fullName>
                <label>田径场</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/ReceiveAddress__c.field-meta.xml
<CustomField>
    <fullName>ReceiveAddress__c</fullName>
    <label>领取地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/ReceiveContact__c.field-meta.xml
<CustomField>
    <fullName>ReceiveContact__c</fullName>
    <label>领取联系人</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/ReceiveContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ReceiveContactPhone__c</fullName>
    <label>领取联系方式</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/ReturnAddress__c.field-meta.xml
<CustomField>
    <fullName>ReturnAddress__c</fullName>
    <label>归还地址</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/ReturnContact__c.field-meta.xml
<CustomField>
    <fullName>ReturnContact__c</fullName>
    <label>归还联系人</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/ReturnContactPhone__c.field-meta.xml
<CustomField>
    <fullName>ReturnContactPhone__c</fullName>
    <label>归还联系方式</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TeachingSupplyReceiveAndReutrnContact__mdt/fields/SecondaryCollege__c.field-meta.xml
<CustomField>
    <fullName>SecondaryCollege__c</fullName>
    <inlineHelpText>若该条记录的教学地点中的教学用品不归属具体的二级学院管理，请保留此字段为空值。</inlineHelpText>
    <label>学院</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>人工智能学院</fullName>
            </value>
            <value>
                <fullName>体育学院</fullName>
            </value>
            <value>
                <fullName>化学化工学院</fullName>
            </value>
            <value>
                <fullName>地理与资源科学学院</fullName>
            </value>
            <value>
                <fullName>外国语学院</fullName>
            </value>
            <value>
                <fullName>建筑工程学院</fullName>
            </value>
            <value>
                <fullName>张大千美术学院</fullName>
            </value>
            <value>
                <fullName>政治与公共管理学院</fullName>
            </value>
            <value>
                <fullName>教育科学学院</fullName>
            </value>
            <value>
                <fullName>数学与信息科学学院</fullName>
            </value>
            <value>
                <fullName>文学院</fullName>
            </value>
            <value>
                <fullName>物理与电子信息工程学院</fullName>
            </value>
            <value>
                <fullName>生命科学学院</fullName>
            </value>
            <value>
                <fullName>经济与管理学院</fullName>
            </value>
            <value>
                <fullName>范长江新闻学院</fullName>
            </value>
            <value>
                <fullName>音乐学院</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ClassTimesGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>1(8:20-9:05)</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>2(9:15-10:00)</label>
    </customValue>
    <customValue>
        <fullName>3</fullName>
        <label>3(10:20-11:05)</label>
    </customValue>
    <customValue>
        <fullName>4</fullName>
        <label>4(11:15-12:00)</label>
    </customValue>
    <customValue>
        <fullName>5</fullName>
        <label>5(13:50-14:35)</label>
    </customValue>
    <customValue>
        <fullName>6</fullName>
        <label>6(14:45-15:30)</label>
    </customValue>
    <customValue>
        <fullName>7</fullName>
        <label>7(15:50-16:35)</label>
    </customValue>
    <customValue>
        <fullName>8</fullName>
        <label>8(16:45-17:30)</label>
    </customValue>
    <customValue>
        <fullName>9</fullName>
        <label>9(19:00-19:45)</label>
    </customValue>
    <customValue>
        <fullName>10</fullName>
        <label>10(19:55-20:40)</label>
    </customValue>
    <customValue>
        <fullName>11</fullName>
        <label>11(20:50-21:35)</label>
    </customValue>
    <masterLabel>上课节次</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TeachingLocationGlobal.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>MingdeBuilding</fullName>
        <label>明德楼</label>
    </customValue>
    <customValue>
        <fullName>BoyaBuilding</fullName>
        <label>伯牙楼</label>
    </customValue>
    <customValue>
        <fullName>HongwenBuilding</fullName>
        <label>弘文楼</label>
    </customValue>
    <customValue>
        <fullName>DaqianBuilding</fullName>
        <label>大千楼</label>
    </customValue>
    <customValue>
        <fullName>GezhiBuilding</fullName>
        <label>格致楼</label>
    </customValue>
    <customValue>
        <fullName>TrainingCenter</fullName>
        <label>培训中心</label>
    </customValue>
    <customValue>
        <fullName>X1stPracticalTrainingBuilding</fullName>
        <label>第一实训楼</label>
    </customValue>
    <customValue>
        <fullName>X2ndPracticalTrainingBuilding</fullName>
        <label>第二实训楼</label>
    </customValue>
    <customValue>
        <fullName>X3rdPracticalTrainingBuilding</fullName>
        <label>第三实训楼</label>
    </customValue>
    <customValue>
        <fullName>X1stPlayground</fullName>
        <label>第一运动场</label>
    </customValue>
    <customValue>
        <fullName>X2ndPlayground</fullName>
        <label>第二运动场</label>
    </customValue>
    <customValue>
        <fullName>X3rdPlayground</fullName>
        <label>第三运动场</label>
    </customValue>
    <customValue>
        <fullName>X4thPlayground</fullName>
        <label>第四运动场</label>
    </customValue>
    <customValue>
        <fullName>X5thPlayground</fullName>
        <label>第五运动场</label>
    </customValue>
    <customValue>
        <fullName>GroundTrackField</fullName>
        <label>田径场</label>
    </customValue>
    <masterLabel>教学地点</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RS_TeachingSupply_Before_Hdl.cls
/**
 * @description: TeachingSupplyBorrowingApplication__c BeforeInsert, BeforeUpdate trigger handler
 * @author: AnonyEast
 * @date: 2023-03-13
 */
public with sharing class RS_TeachingSupply_Before_Hdl implements Triggers.Handler {
    public void handle() {
        try {
            // 更新后的对象
            List<TeachingSupplyBorrowingApplication__c> lstNewBorrowingApplication = (List<TeachingSupplyBorrowingApplication__c>)Trigger.new;
            // 更新前的对象
            Map<Id, TeachingSupplyBorrowingApplication__c> mapOldBorrowingApplication = (Map<Id, TeachingSupplyBorrowingApplication__c>)Trigger.oldMap;
            // 借用开始时间、借用结束时间字段赋值(仅限按日期和节次借用)
            setBorrowingStartAndEndDatetime(lstNewBorrowingApplication);
            // 存储审批通过的对象
            List<TeachingSupplyBorrowingApplication__c> lstApprovedBorrowingApplication = new List<TeachingSupplyBorrowingApplication__c>();
            // 判断审批状态
            for (TeachingSupplyBorrowingApplication__c objBorrowing : lstNewBorrowingApplication) {
                // 获取更新前的审批状态
                String strOldStatus = mapOldBorrowingApplication.get(objBorrowing.Id).ApprovalStatus__c;
                // 审批通过
                if (objBorrowing.ApprovalStatus__c == RS_Constants.PICKLIST_APPROVAL_STATUS_APPROVED && strOldStatus != objBorrowing.ApprovalStatus__c) {
                    lstApprovedBorrowingApplication.add(objBorrowing);
                }
            }
            if (!lstApprovedBorrowingApplication.isEmpty()) {
                // 领取/归还联系信息赋值
                setReceiveAndReutrnContact(lstApprovedBorrowingApplication);
            }
        } catch (Exception ex) {
            RS_Logger_Cmn.createLog('TeachingSupply_BeforeTrg_Exception',ex,'RS_TeachingSupply_Before_Hdl.handle');
        }
    }

    /**
     * @description 借用开始时间、借用结束时间字段赋值(仅限按日期和节次借用)
     * @param lstBorrowingApplication 教学用品借用申请列表
     */
    public static void setBorrowingStartAndEndDatetime(List<TeachingSupplyBorrowingApplication__c> lstBorrowingApplication) {
        // 从节次时间表(ClassTimesSchedule__mdt)获取上课时间
        List<ClassTimesSchedule__mdt> lstClassTimesSchedule = [
            SELECT ClassTimes__c,ClassStartTime__c,ClassEndTime__c
            FROM ClassTimesSchedule__mdt
        ];
        // 将节次与上课时间、下课时间的映射封装到Map
        Map<Integer,ClassTimesSchedule__mdt> mapClassTimesSchedule = new Map<Integer,ClassTimesSchedule__mdt>();
        for (ClassTimesSchedule__mdt mdtClassTimesSchedule : lstClassTimesSchedule) {
            mapClassTimesSchedule.put(Integer.valueOf(mdtClassTimesSchedule.ClassTimes__c),mdtClassTimesSchedule);
        }
        
        for(TeachingSupplyBorrowingApplication__c objBorrowingApplication : lstBorrowingApplication){
            try {
                // 按日期和节次借用
                if (objBorrowingApplication.RecordTypeId == RS_Constants.BORROWING_BY_CLASS_TIMES_RECORD_TYPE_ID) {
                    // 获取上课时间
                    ClassTimesSchedule__mdt mdtStartClassTimesSchedule = mapClassTimesSchedule.get(Integer.valueOf(objBorrowingApplication.BorrowingStartClassTimes__c));
                    String strBorrowingStartTime = mdtStartClassTimesSchedule.ClassStartTime__c;
                    // 获取上课时间的小时和分钟
                    List<String> lstBorrowingStartTimeSplit = strBorrowingStartTime.split(':');
                    // 按年月日时分秒创建开始借用日期和时间的Datetime实例
                    Datetime datetimeBorrowingStartDateAndTime = Datetime.newInstance(objBorrowingApplication.BorrowingStartDate__c.year(),objBorrowingApplication.BorrowingStartDate__c.month(),objBorrowingApplication.BorrowingStartDate__c.day(),Integer.valueOf(lstBorrowingStartTimeSplit.get(0)),Integer.valueOf(lstBorrowingStartTimeSplit.get(1)),0);
                    // 借用开始时间赋值
                    objBorrowingApplication.BorrowingStartDateAndTime__c = datetimeBorrowingStartDateAndTime;
                    // 获取下课时间
                    ClassTimesSchedule__mdt mdtEndClassTimesSchedule = mapClassTimesSchedule.get(Integer.valueOf(objBorrowingApplication.BorrowingEndClassTimes__c));
                    String strBorrowingEndTime = mdtEndClassTimesSchedule.ClassEndTime__c;
                    // 获取下课时间的小时和分钟
                    List<String> lstBorrowingEndTimeSplit = strBorrowingEndTime.split(':');
                    // 按年月日时分秒创建结束借用日期和时间的Datetime实例
                    Datetime datetimeBorrowingEndDateAndTime = Datetime.newInstance(objBorrowingApplication.BorrowingEndDate__c.year(),objBorrowingApplication.BorrowingEndDate__c.month(),objBorrowingApplication.BorrowingEndDate__c.day(),Integer.valueOf(lstBorrowingEndTimeSplit.get(0)),Integer.valueOf(lstBorrowingEndTimeSplit.get(1)),0);
                    // 借用结束时间赋值
                    objBorrowingApplication.BorrowingEndDateAndTime__c = datetimeBorrowingEndDateAndTime;
                }
            } catch (Exception ex) {
                objBorrowingApplication.BorrowingStartDateAndTime__c = null;
                objBorrowingApplication.BorrowingEndDateAndTime__c = null;
                RS_Logger_Cmn.createLog('TeachingSupply_Exception',ex,'RS_TeachingSupply_Before_Hdl.setBorrowingStartAndEndDatetime');
            }
        }
    }

    /**
     * @description 领取/归还联系信息赋值
     * @param lstBorrowingApplication: 审批通过的教学用品借用申请申请记录
     */
    public static void setReceiveAndReutrnContact(List<TeachingSupplyBorrowingApplication__c> lstBorrowingApplication){
        // 查询各二级学院Id
        Map<Id,Account> mapSecondryCollage = RS_SObjectUtil_Cmn.getSecondryCollegeMap();
        // 获取教学用品领取归还联系信息
        List<TeachingSupplyReceiveAndReutrnContact__mdt> lstReceiveAndReutrnContact = [
            SELECT Id, ReceiveContact__c, Location__c, ReceiveContactPhone__c, ReturnContact__c, ReturnContactPhone__c, Active__c, ReceiveAddress__c, SecondaryCollege__c, ReturnAddress__c 
            FROM TeachingSupplyReceiveAndReutrnContact__mdt
            WHERE Active__c = true
        ];
        // 将地点与联系信息的映射封装到Map
        Map<String,List<TeachingSupplyReceiveAndReutrnContact__mdt>> mapReceiveAndReutrnContactByLocation = new Map<String,List<TeachingSupplyReceiveAndReutrnContact__mdt>>();
        // 开始封装
        for (TeachingSupplyReceiveAndReutrnContact__mdt mdtReceiveAndReutrnContact : lstReceiveAndReutrnContact) {
            // 同一个教学地点可能有多个联系信息
            List<TeachingSupplyReceiveAndReutrnContact__mdt> lstReceiveAndReutrnContactByLocation = mapReceiveAndReutrnContactByLocation.get(mdtReceiveAndReutrnContact.Location__c);
            if (lstReceiveAndReutrnContactByLocation != null && lstReceiveAndReutrnContactByLocation.size() > 0){
                lstReceiveAndReutrnContactByLocation = mapReceiveAndReutrnContactByLocation.get(mdtReceiveAndReutrnContact.Location__c);
                lstReceiveAndReutrnContactByLocation.add(mdtReceiveAndReutrnContact);
                mapReceiveAndReutrnContactByLocation.put(mdtReceiveAndReutrnContact.Location__c, lstReceiveAndReutrnContactByLocation);
            }else{
                lstReceiveAndReutrnContactByLocation = new List<TeachingSupplyReceiveAndReutrnContact__mdt>();
                lstReceiveAndReutrnContactByLocation.add(mdtReceiveAndReutrnContact);
                mapReceiveAndReutrnContactByLocation.put(mdtReceiveAndReutrnContact.Location__c, lstReceiveAndReutrnContactByLocation);
            }
        }
        
        // 开始完成领取/归还联系信息赋值
        for (TeachingSupplyBorrowingApplication__c objBorrowing : lstBorrowingApplication){
            if (mapReceiveAndReutrnContactByLocation.get(objBorrowing.Location__c) != null){
                List<TeachingSupplyReceiveAndReutrnContact__mdt> lstReceiveAndReutrnContactByLocation = mapReceiveAndReutrnContactByLocation.get(objBorrowing.Location__c);
                // 当前地点下学院为空的联系信息
                TeachingSupplyReceiveAndReutrnContact__mdt mdtReceiveAndReutrnContactWithNullCollege;
                // 当前地点下与借用申请的学院相同的联系信息
                TeachingSupplyReceiveAndReutrnContact__mdt mdtReceiveAndReutrnContactWithSameCollege;
                for (TeachingSupplyReceiveAndReutrnContact__mdt mdtReceiveAndReutrnContact : lstReceiveAndReutrnContactByLocation) {
                    // 学院为空的联系信息
                    if (mdtReceiveAndReutrnContact.SecondaryCollege__c == null) {
                        mdtReceiveAndReutrnContactWithNullCollege = mdtReceiveAndReutrnContact;
                    }
                    // 与借用申请的学院相同的联系信息
                    if (mapSecondryCollage.get(objBorrowing.SecondaryCollegeLookup__c) != null && mdtReceiveAndReutrnContact.SecondaryCollege__c == mapSecondryCollage.get(objBorrowing.SecondaryCollegeLookup__c).Name) {
                        mdtReceiveAndReutrnContactWithSameCollege = mdtReceiveAndReutrnContact;
                    }
                }
                if (mdtReceiveAndReutrnContactWithSameCollege != null) {
                    objBorrowing.ReceiveContact__c = mdtReceiveAndReutrnContactWithSameCollege.ReceiveContact__c;
                    objBorrowing.ReceiveContactPhone__c = mdtReceiveAndReutrnContactWithSameCollege.ReceiveContactPhone__c;
                    objBorrowing.ReceiveAddress__c = mdtReceiveAndReutrnContactWithSameCollege.ReceiveAddress__c;
                    objBorrowing.ReturnContact__c = mdtReceiveAndReutrnContactWithSameCollege.ReturnContact__c;
                    objBorrowing.ReturnContactPhone__c = mdtReceiveAndReutrnContactWithSameCollege.ReturnContactPhone__c;
                    objBorrowing.ReturnAddress__c = mdtReceiveAndReutrnContactWithSameCollege.ReturnAddress__c;
                }
                else if (mdtReceiveAndReutrnContactWithNullCollege != null){
                    objBorrowing.ReceiveContact__c = mdtReceiveAndReutrnContactWithNullCollege.ReceiveContact__c;
                    objBorrowing.ReceiveContactPhone__c = mdtReceiveAndReutrnContactWithNullCollege.ReceiveContactPhone__c;
                    objBorrowing.ReceiveAddress__c = mdtReceiveAndReutrnContactWithNullCollege.ReceiveAddress__c;
                    objBorrowing.ReturnContact__c = mdtReceiveAndReutrnContactWithNullCollege.ReturnContact__c;
                    objBorrowing.ReturnContactPhone__c = mdtReceiveAndReutrnContactWithNullCollege.ReturnContactPhone__c;
                    objBorrowing.ReturnAddress__c = mdtReceiveAndReutrnContactWithNullCollege.ReturnAddress__c;
                }
                else{
                    objBorrowing.ReceiveContact__c = '请联系系统管理员配置"领取/归还联系信息"';
                }
            }else{
                objBorrowing.ReceiveContact__c = '请联系系统管理员配置"领取/归还联系信息"';
            }
        }
    }
}